AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - bin/*
    - db/schema.rb
  TargetRubyVersion: 2.4

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - lib/tasks/*.rake
    - spec/**/*.rb
    - app/**/concerns/*.rb
    - db/seeds/*.seeds.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
